### ISSUE TITLE
Uploading the Application to Your Batch Apps Service

### ISSUE THREAD

**Issue by spevilgenius** [Azure/azure-batch-apps-blender#7] opened 2016-06-30 22:24 UTC
In step 6 of the sample in this heading it states that you should have an option to upload the cloud assembly except that I do not see that option. I only have the Application Package option. Is there something else I need to do?

**Comment by annatisch** [comment] 2016-07-01 01:26
Hi @spevilgenius,
This Blender sample was originally created for the now-deprecated Batch Apps service. So a number of features described in the steps are no longer available.

I have made a start on porting this sample to the raw Batch service on my fork here:
https://github.com/annatisch/azure-batch-apps-blender/tree/dev

I haven't updated the documentation yet. If you're interested I can go over the differences in more detail and help you set it up (though not all features have been ported yet, and some are still rather rudimentary) - and at the same time update the setup documentation :)

Thanks,
Anna

**Comment by unclenorton** [comment] 2016-07-02 17:39
@annatisch Did you manage to get it actually working? I tried your fork and get all sorts of issues, from dependencies and missing imports to missing attributes in the existing classes.

**Comment by annatisch** [comment] 2016-07-05 16:57
Hi @unclenorton,
Yes to an extent it does work (it will at least load).
However it's true that I haven't yet updated the dependencies installer script.
I currently have the following packages installed in Blenders Python package (most of the are dependencies of each other - installing the top two should take care of most of them):

- azure-storage
- azure-batch
- msrest
- msrestazure
- requests
- requests-oauthlib
- oauthlib
- pkg-resources
- isodate
- chardet
- certifi
- keyring

Let me know if this helps at all!

**Comment by RomainQueraud** [comment] 2016-07-22 10:03
Hi @annatisch and thanks for your work and your help !

I'm following your answer on [StackOverflow](http://stackoverflow.com/questions/38508956/existing-code-on-github-principal-functions-never-called/38511603#38511603).

Using your updated code, I managed to make it work further than where I was before. I had to make minor modifications : 

- rename the "batchapps_blender" folder into "batched_blender"
- in "shared.py" in the `start() `method, the BatchServiceClientConfiguration didn't exist in azure.batch. So I had to remove the `batch_config = ... ` line and change the `batch = ...` by : `batch = az_batch.BatchServiceClient(batch_creds, base_url=self.cfg['endpoint'])`

So the plugin starts, uploads the assets, creatse the pools, the job and the task. In the azure portal I can see that the status of the task changes to "completed" after some time (The job remains active), so it imagine that it works ! 

So my question is, where can I find the ouput image of the render ? Because nothing appears in the output blob of my storage account.

Thank you again for your help !

Romain

**Comment by annatisch** [comment] 2016-07-22 15:53
@RomainQueraud  - you're very welcome. I enjoy working with Blender :)
Thanks for trying out the new code - I look forward to your feedback!

* Yes - sorry about that - I've been in the process of renaming the plugin (as Batch Apps was the old service that is deprecated) but I hadn't propagated it through to the directory name as I didn't yet want to loose the git file histories. Sorry I didn't point this out sooner.
* Yes, the configuration objects were dropped as part of a breaking change in the Azure SDK for Python RC4, which I hadn't updated to yet. I'll try to clean this up :)

Interesting about the error for pools... are any useful messages printed into the Blender console output (or in terminal if on Mac OS)?
Another error you may encounter that I haven't fixed yet is the checking for already uploaded assets.
When resubmitting the same file this errors, but if you save the blend file to a new name it should submit okay.

Thanks,
Anna

**Comment by RomainQueraud** [comment] 2016-07-29 15:58
Hi @annatisch 

I didn't encountered the error for the asset, I tried to delete the asset and upload the updated one with the new name and I had no problems.

However, I encountered some errors, I will try to tell you how to reproduce them. I have difficulties to follow what happens in the code as I not used to python and I find it difficult to follow the call hierarchy and the variable assignment. I am maybe not doing it the right way (Visual studio 2015 and F12 to find declaration).

1.  In the submit job panel, if I set the start frame to 1 and end frame at 250, it keeps telling me "Submission now processing" and an error, you can find the log attached (file 1). 
And I don't understand what it should be used for, isn't the frame range normally used to render video ? [error-1.txt](https://github.com/Azure/azure-batch-apps-blender/files/390905/error-1.txt)

2.  If I click on the Pool panel after submitting a job, I also have an error. The error doesn’t appear when there is no pool.
The error only appears when the pool had been created automatically by the job.
Also, changing the instance number in the job panel doesn't seem to work. It always takes the last number specified when creating a pool in the pool panel.
[error-2.txt](https://github.com/Azure/azure-batch-apps-blender/files/390904/error-2.txt)

3. An other error if I click on "import sequence" in the job panel. By the way, I don't understand what this button is supposed to do ?
[error-3.txt](https://github.com/Azure/azure-batch-apps-blender/files/390903/error-3.txt)

4. An other error if I try to delete a pool in Blender after I started it manually. 
[error-4.txt](https://github.com/Azure/azure-batch-apps-blender/files/390906/error-4.txt)

Can you give me an hint on what to modify or on where to look for the information to change ?

Thanks,
Romain

**Comment by annatisch** [comment] 2016-08-01 23:57
Thanks @RomainQueraud,

I'm going to push out the following pug fixes in the next couple of days:
 - The excess BatchServiceClientConfiguration object you mentioned earlier has been removed.
 - The 100 frame limit on job submissions has been fixed (issue 1 above)
 - I've fixed the pool page loading error, this was due to some of the pools being poorly named by the plugin.
 - The pools should now take their size from the input on the submission panel rather than the pools panel.
 - The detecting of already uploaded assets

The import sequence button is supposed to download images directly into Blender's sequence editor. If you open up this view you should see them there and be able to scrub/play through the sequence. This will only work if the job is complete and if the pool that the job was run on is a) still running and b) not been re-imaged since the job was run. The error you're seeing here looks like it might be that the pool has been shut down. This behaviour will be fixed once I implement persisting rendered frames to storage. There's probably lots more that can be done to make this more robust, so if you think the error you're seeing isn't related, let me know and I'll investigate further.

On this note I would recommend not using Auto-Pools until I have amended this - as there's a chance the pool will shut down before you can access the outputs - so better to create a new persistent pool, then shut it down manually once complete.

Cheers,
Anna

**Comment by annatisch** [comment] 2016-08-03 19:54
Hi @RomainQueraud,

So I've committed a bunch of fixes including those listed above. I've also officially renamed the plugin directory to batched_blender and deleted the Blender.Cloud project to avoid further confusion.
I've temporarily disabled auto pools - as mentioned above, until I get outputs persisted to storage there's not much use to them. And they are also crashing Blender in the pools display which I can't figure out for now....

I've also added some VM configuration to the User Preferences window for the plugin, so you can select VM size etc and started to fix up the readme documentation to be more useful (still more to be done though...)

Cheers,
Anna

**Comment by annatisch** [comment] 2017-02-22 23:13
Closing due to inactivity - please reopen if you're still experiencing issues related to this problem :)

**Closed by annatisch** 2017-02-22 23:13 UTC
